---
title: "spotify"
author: "yp2533"
date: "2019/11/25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction
Explain why you chose this topic, and the questions you are interested in studying. Provide context for readers who are not familiar with the topic.

## Data sources
Describe the data sources: who is responsible for collecting the data? How is it collected? If there were a choice of options, explain how you chose.

Provide some basic information about the dataset: types of variables, number of records, etc.

Describe any known issues / problems about the data.

(You should be able to write this section without actually working with the data.)

## Data transformation
Describe the process of getting the data into a form in which you could work with it in R.

## Missing values
Describe any patterns you discover in missing values.

## Results
Provide a short nontechnical summary of the most revealing findings of your analysis written for a nontechnical audience. Take extra care to clean up your graphs, ensuring that best practices for presentation are followed, as described in the audience ready style section below.

## Interactive component
Select one (or more) of your key findings to present in an interactive format. Be selective in the choices that you present to the user; the idea is that in 5-10 minutes, users should have a good sense of the question(s) that you are interested in and the trends you’ve identified in the data. In other words, they should understand the value of the analysis, be it business value, scientific value, general knowledge, etc.

Interactive graphs must follow all of the best practices as with static graphs in terms of perception, labeling, accuracy, etc.

You may choose the tool (D3, Shiny, or other) The complexity of your tool will be taken into account: we expect more complexity from a higher-level tool like Shiny than a lower-level tool like D3, which requires you to build a lot from scratch.

Make sure that the user is clear on what the tool does and how to use it.

It may be possible to include the interactive component directly in your report. If not, publish your graph somewhere on the web and provide a link in your report in the interactive section. The obvious choices are blockbuilder.org to create a block for D3, and shinyapps.io for Shiny apps but other options are fine. You are encouraged to share experiences on Piazza to help classmates with the publishing process.

Note: the interactive component is worth approximately 25% of the final project grade. Therefore, do not spend 90% of your time on it… concentrate on the exploratory data analysis piece.

